version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: karting_bot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: